// vue-cafeteria/src/components/form/SelectField.vue
<script setup>
// COMPONENTE: Campo de selección reutilizable (select)
// Las opciones llegan por props. Componente independiente y movible.
defineProps({
  label: String,
  modelValue: String,
  error: String,
  options: { type: Array, default: () => [] },
})
defineEmits(['update:modelValue'])
</script>

<template>
  <div class="field">
    <label>{{ label }}</label>
    <select
      :value="modelValue"
      :class="{ invalid: error }"
      @change="$emit('update:modelValue', $event.target.value)"
    >
      <option value="">Seleccione...</option>
      <option v-for="opt in options" :key="opt" :value="opt">{{ opt }}</option>
    </select>
    <span v-if="error" class="error-msg">{{ error }}</span>
  </div>
</template>

// react-cafeteria/src/components/form/SelectField.jsx
// COMPONENTE: Campo de selección reutilizable (select)
// Las opciones llegan por props. Es un componente independiente:
// para moverlo solo cambias su posición en el formulario.
export default function SelectField({
  label,
  name,
  value,
  onChange,
  error,
  options = [],
}) {
  return (
    <div className="field">
      <label htmlFor={name}>{label}</label>
      <select
        id={name}
        name={name}
        value={value}
        onChange={onChange}
        className={error ? 'invalid' : ''}
      >
        <option value="">Seleccione...</option>
        {options.map((opt) => (
          <option key={opt} value={opt}>
            {opt}
          </option>
        ))}
      </select>
      {error && <span className="error-msg">{error}</span>}
    </div>
  )
}
