// vue-cafeteria/src/components/form/TextAreaField.vue
<script setup>
// COMPONENTE: Área de texto reutilizable (textarea)
defineProps({
  label: String,
  modelValue: String,
  error: String,
  placeholder: { type: String, default: '' },
})
defineEmits(['update:modelValue'])
</script>

<template>
  <div class="field">
    <label>{{ label }}</label>
    <textarea
      :value="modelValue"
      :placeholder="placeholder"
      :class="{ invalid: error }"
      @input="$emit('update:modelValue', $event.target.value)"
    ></textarea>
    <span v-if="error" class="error-msg">{{ error }}</span>
  </div>
</template>

// react-cafeteria/src/components/form/TextAreaField.jsx
// COMPONENTE: Área de texto reutilizable (textarea)
export default function TextAreaField({
  label,
  name,
  value,
  onChange,
  error,
  placeholder = '',
}) {
  return (
    <div className="field">
      <label htmlFor={name}>{label}</label>
      <textarea
        id={name}
        name={name}
        value={value}
        onChange={onChange}
        placeholder={placeholder}
        className={error ? 'invalid' : ''}
      />
      {error && <span className="error-msg">{error}</span>}
    </div>
  )
}
