// vue-cafeteria/src/App.vue
<script setup>
import Navbar from './components/Navbar.vue'
import Hero from './components/Hero.vue'
import Menu from './components/Menu.vue'
import About from './components/About.vue'
import Reservation from './components/Reservation.vue'
import Footer from './components/Footer.vue'

// COMPONENTE RAÍZ: arma la página uniendo todos los componentes.
// La estructura de la interfaz es clara: cada sección es un componente.
</script>

<template>
  <Navbar />
  <Hero />
  <Menu />
  <About />
  <Reservation />
  <Footer />
</template>

// react-cafeteria/src/App.jsx
import Navbar from './components/Navbar'
import Hero from './components/Hero'
import Menu from './components/Menu'
import About from './components/About'
import Reservation from './components/Reservation'
import Footer from './components/Footer'

// COMPONENTE RAÍZ: arma la página uniendo todos los componentes.
// La estructura de la interfaz se ve clara: cada sección es un componente.
export default function App() {
  return (
    <>
      <Navbar />
      <Hero />
      <Menu />
      <About />
      <Reservation />
      <Footer />
    </>
  )
}
