// react-cafeteria/src/components/Navbar.jsx
import { useState } from 'react'

// COMPONENTE: Barra de navegación responsive con menú hamburguesa
export default function Navbar() {
  const [open, setOpen] = useState(false)

  return (
    <nav className="navbar">
      <div className="container">
        <a href="#inicio" className="logo">☕ Café Aroma</a>

        <button
          className="nav-toggle"
          onClick={() => setOpen(!open)}
          aria-label="Abrir menú"
        >
          ☰
        </button>

        <ul className={`nav-links ${open ? 'open' : ''}`}>
          <li><a href="#inicio" onClick={() => setOpen(false)}>Inicio</a></li>
          <li><a href="#menu" onClick={() => setOpen(false)}>Menú</a></li>
          <li><a href="#nosotros" onClick={() => setOpen(false)}>Nosotros</a></li>
          <li><a href="#reservar" onClick={() => setOpen(false)}>Reservar</a></li>
        </ul>
      </div>
    </nav>
  )
}

// vue-cafeteria/src/components/Navbar.vue
<script setup>
import { ref } from 'vue'

// COMPONENTE: Barra de navegación responsive con menú hamburguesa
const open = ref(false)
</script>

<template>
  <nav class="navbar">
    <div class="container">
      <a href="#inicio" class="logo">☕ Café Aroma</a>

      <button class="nav-toggle" @click="open = !open" aria-label="Abrir menú">
        ☰
      </button>

      <ul class="nav-links" :class="{ open }">
        <li><a href="#inicio" @click="open = false">Inicio</a></li>
        <li><a href="#menu" @click="open = false">Menú</a></li>
        <li><a href="#nosotros" @click="open = false">Nosotros</a></li>
        <li><a href="#reservar" @click="open = false">Reservar</a></li>
      </ul>
    </div>
  </nav>
</template>
