// vue-cafeteria/src/components/Footer.vue
<script setup>
// COMPONENTE: Pie de página
</script>

<template>
  <footer class="footer">
    <div class="container">
      <h3>☕ Café Aroma</h3>
      <ul class="footer-links">
        <li><a href="#inicio">Inicio</a></li>
        <li><a href="#menu">Menú</a></li>
        <li><a href="#nosotros">Nosotros</a></li>
        <li><a href="#reservar">Reservar</a></li>
      </ul>
      <p>📍 Av. Principal 123 · 📞 099 999 9999</p>
      <p>© 2026 Café Aroma — Hecho con Vue</p>
    </div>
  </footer>
</template>

// react-cafeteria/src/components/Footer.jsx
// COMPONENTE: Pie de página
export default function Footer() {
  return (
    <footer className="footer">
      <div className="container">
        <h3>☕ Café Aroma</h3>
        <ul className="footer-links">
          <li><a href="#inicio">Inicio</a></li>
          <li><a href="#menu">Menú</a></li>
          <li><a href="#nosotros">Nosotros</a></li>
          <li><a href="#reservar">Reservar</a></li>
        </ul>
        <p>📍 Av. Principal 123 · 📞 099 999 9999</p>
        <p>© 2026 Café Aroma — Hecho con React</p>
      </div>
    </footer>
  )
}
