// vue-cafeteria/src/components/Hero.vue
<script setup>
// COMPONENTE: Sección principal (Hero) con llamada a la acción
</script>

<template>
  <header class="hero" id="inicio">
    <div class="container">
      <h1>El mejor café de la ciudad</h1>
      <p>
        Disfruta de granos seleccionados, repostería artesanal y un ambiente
        acogedor. Reserva tu mesa y vive la experiencia Café Aroma.
      </p>
      <a href="#reservar" class="btn">Reservar mesa</a>
    </div>
  </header>
</template>

// react-cafeteria/src/components/Hero.jsx
// COMPONENTE: Sección principal (Hero) con llamada a la acción
export default function Hero() {
  return (
    <header className="hero" id="inicio">
      <div className="container">
        <h1>El mejor café de la ciudad</h1>
        <p>
          Disfruta de granos seleccionados, repostería artesanal y un ambiente
          acogedor. Reserva tu mesa y vive la experiencia Café Aroma.
        </p>
        <a href="#reservar" className="btn">Reservar mesa</a>
      </div>
    </header>
  )
}
